### ISSUE TITLE
implement chart testing

### ISSUE THREAD

**Issue by edevosc2c** [georchestra/helm-georchestra#21]
https://github.com/helm/chart-testing-action

**Comment by edevosc2c** [comment]
done

**Comment by fvanderbiest** [comment]
done where what how ? which milestone ?
Please provide PR ref or commit ref :-)

**Comment by edevosc2c** [comment]
oops yes! I've edited my message

**Comment by fvanderbiest** [comment]
A bit of description also would do no harm: which problems does this fix ?
(helpful for those in the community who do not master k8s - yet)
Thanks !

**Comment by fvanderbiest** [comment]
PRs should be the rule, so that the community has a word to say / is notified 
Thanks Emilien :-)
