### ISSUE TITLE
provide a "maintenance mode"

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/helm-georchestra#42]
Hi,
when using the internal ldap and postgresql databases, at some point, you will have to run maintenance operations, at least for the upgrades. In that situation, it might be useful to have only the needed services running (the databases, but not the deployments depending on them). Something like switching into "maintenance mode". This could be done using a maintenanceMode variable in Values.yaml where only the databases would run when it's on.
This would also ensure that the other deployments and such restart properly after you get out of the maintenance mode. 
What do you think ?

**Comment by edevosc2c** [comment]
We can expose the ability to set replicas count for each apps, this way an administrator can easily turn off some of the apps. Internally this will scale the Deployment(s) to 0 so 0 pod.

I don't think a parameter `maintenance mode` makes sense, I would prefer to have a setting like stated above and write in the README in case of maintenance: "do that and that".

**Comment by jeanpommier** [comment]
Yup, sounds fine. Except that it might hint that you could set replica count above 1. Which is not the case for quite a few apps, right ? At least GN and standard GS. But maybe just documenting that cardinality is [0:1] for those is enough

**Comment by jeanpommier** [comment]
Reviving this ticket. What's the current restore strategy ?

**Comment by edevosc2c** [comment]
What do you mean by restore strategy?

I still think providing the ability to set replica counts is the best idea.

**Comment by jeanpommier** [comment]
OK, fine. If you're up to it, I'll make a PR

**Comment by edevosc2c** [comment]
Fulfilled in https://github.com/georchestra/helm-georchestra/pull/69
