### ISSUE TITLE
Add support for built-in ingress

### ISSUE THREAD

**Issue by edevosc2c** [georchestra/helm-georchestra#5]
Add the ability to have the ingress built in the helm chart.

**Comment by jeanmi151** [comment]
I started this work

**Comment by fvanderbiest** [comment]
Can you share more about the why / pros / cons / implications ?
Thanks a lot !

**Comment by jeanmi151** [comment]
actually, when we deploy a default georchestra with this helm chart, it is not "working" as we can not access it.
The main goal is to git clone, push the chart on a kube instance and it is ready for testing, nothing else to do (even for us for testing/deploy fast it would be great) !

**Comment by fvanderbiest** [comment]
awesome !

**Comment by fvanderbiest** [comment]
traefik-based ?

**Comment by jeanpommier** [comment]
We'll probably have to cover at least traefik and nginx ingresses. But anyway, covering any possible situation might be tricky. 

I have some generic ingress yaml file, that is almost totally configured in the chart's values file. Can give it to you if you want (I believe it was created by a `helm create`)

**Comment by edevosc2c** [comment]
Ingress is an abstraction that work for all the ingress controllers: traefik, NGINX, haproxy and more.

We do not need to add specific parameters so we can built-in a generic ingress manifest with the ability to adapt it through helm values if needed.
