### ISSUE TITLE
elasticsearch is running as a deployment

### ISSUE THREAD

**Issue by edevosc2c** [georchestra/helm-georchestra#55]
elasticsearch is a database and it is running a deployment. this is bad because it means multiple elasticsearch can be created at the same time for the same PVC so the **same data**!

You can't run multiple elasticsearch with the same data, or they will get corrupted. ideally we should move to a StatefulSet so that only one pod can use the same data at the same time, any additional statefulset won't start with the same PVC.

Maybe @pmauduit could explain why deployment was the choice for elasticsearch?

**Comment by pmauduit** [comment]
> Maybe @pmauduit could explain why deployment was the choice for elasticsearch?

The Elasticsearch being deployed in the context of the georchestra helm chart is only meant to be used by GeoNetwork. As it is mainly used for indexing the metadata stored in the postgresql database, it has been judged that losing the single elastic deployment could be an acceptable risk (as it is reconstructible in a fair amount of time), and the chart should not plan to scale it to more than 1 initially.

feel free to improve the current state though.
